project:
  type: website

website:
  title: "Satyabrata pal" 
  site-url: https://www.satyabratapal.xyz
  description: "This is Satyabrata pal's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Series
        href: series.qmd  
      - icon: github
        href: https://github.com/sapal6
      - icon: twitter
        href: https://twitter.com/thecodingprojec
      - icon: youtube
        href: https://www.youtube.com/channel/UCNWi3qvLjYdSAqKnt1uZj-w
  google-analytics: G-6WXK83Q2S1
#########################
# # You can ignore this part in the first step
#       - icon: rss
#         href: blog.xml
#       - text: Ressources
#         menu: 
#           - text: DataViz Portfolio
#             href: dataviz_portfolio.html
#           - text: YARDS
#             href: https://yards.albert-rapp.de/
#           - text: R Weekly
#             href: https://rweekly.org/
#           - text: R Bloggers
#             href: https://www.r-bloggers.com/
#       - text: Archive
#         href: archive.qmd
#   cookie-consent: true
#   twitter-card: 
#     image: thumbnail_blog.png
#     card-style: summary_large_image
#     creator: "@rappa753"

#filters:
#  - code-filename
######################### 

format:
  html:
    theme: litera